### ISSUE TITLE
Gpt

### ISSUE THREAD

**Issue by Azulax90** [Sysys242/Hcaptcha-Hsl-Reversed#1]
how ask to gpt can take 1h ???

**Comment by Azulax90** [comment]
![image](https://user-images.githubusercontent.com/113309764/227768452-1b38c2a4-9e06-4a20-b9c0-5ad89f920e34.png)

**Comment by Sysys242** [comment]
Bro you are retarded af, i told gpt to convert this script to python, to save me some time bc gay, all other shit is me

**Comment by mewzax** [comment]
c vrai qu'il est retardé asf azulax

![image](https://user-images.githubusercontent.com/75091300/227787610-b4e0508e-0756-42a0-9d21-346ab6dde020.png)
